### ISSUE TITLE
Error: no Identity Store Group found matching criteria

### ISSUE THREAD

**Issue by edin-kesetovic** [cloudposse/terraform-aws-sso#17]
## Describe the Bug

```
terraform plan
╷
│ Error: no Identity Store Group found matching criteria
│ [{
│   AttributePath: "DisplayName",
│   AttributeValue: "S3Adminstrators"
│ }]; try different search
│ 
│   with module.sso_account_assignments.data.aws_identitystore_group.this["S3Adminstrators"],
│   on ../../modules/account-assignments/main.tf line 1, in data "aws_identitystore_group" "this":
│    1: data "aws_identitystore_group" "this" {
│ 
╵
╷
│ Error: no Identity Store Group found matching criteria
│ [{
│   AttributePath: "DisplayName",
│   AttributeValue: "Administrators"
│ }]; try different search
│ 
│   with module.sso_account_assignments.data.aws_identitystore_group.this["Administrators"],
│   on ../../modules/account-assignments/main.tf line 1, in data "aws_identitystore_group" "this":
│    1: data "aws_identitystore_group" "this" {
```

## Steps to Reproduce
1. cd ./examples/complete
2. Modify main.tf to replace boilerplate with actual group names and real AWS account ids
3. terraform init
4. terraform plan 
5. See error

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: Linux 
 - Terraform Version [1.0.0, 0.13.0, 0.14.0 ]

**Comment by shmileee** [comment]
In my case I had to manually create groups named `Developers`, `Administrators` & `S3AdministratorAccess` in SSO.

**Comment by nicolaevladescu** [comment]
@edin-kesetovic 

You need to have those groups already present in the AWS SSO configuration, either provisioned via SCIM if you use an external identity source, or manually created like @shmileee pointed out if you use AWS SSO itself as the identity source.

Check the AWS Console AWS SSO page and see if the groups you are searching for are there.

**Comment by mcalhoun** [comment]
Closing. @nicolaevladescu answer above points out the issue. It is really difficult to provide a full working example as that example requires AWS SSO to be setup and configured properly to creating and assigning permission sets, and currently (Aug 2021) there isn't an API (and thus no terraform support) for doing that.
