### ISSUE TITLE
hashicorp/aws 5.0.0 Filter block not expected here.

### ISSUE THREAD

**Issue by elliottohara** [cloudposse/terraform-aws-sso#46]
### Describe the Bug

When using the aws provider >=5.0.0, we get a `filter block not expected here`. 

See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-5-upgrade#data-sourceaws_identitystore_group 

### Expected Behavior

Plan and applies to work on latest version of aws provider

### Steps to Reproduce

terraform init -upgrade a repo using the module
terraform plan

**Comment by Nuru** [comment]
Closing as fixed by #44
